"""Test skeleton writers for audit invariants."""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class FunctionSpec:
    name: str
    signature: str
    args_expr: str
    payable: bool = False


@dataclass
class ContractSpec:
    name: str
    import_path: str
    has_initialize: bool
    constructor_arity: int
    functions: list[FunctionSpec]


class FoundrySkeletonWriter:
    """Generate Foundry-compatible test skeletons and concrete init-gate checks."""

    harness_type = "foundry"
    contract_name = "HoundInvariantSkeletonTest"

    def write(
        self,
        *,
        invariants: list[dict[str, Any]],
        project_dir: Path,
        session_dir: Path,
        proof_plan: dict[str, Any] | None = None,
    ) -> dict[str, Path]:
        repo_dir = Path(project_dir)
        tests_dir = repo_dir / "test" / "security"
        tests_dir.mkdir(parents=True, exist_ok=True)
        contracts = self._scan_contracts(repo_dir)
        skeleton_path = tests_dir / "HoundInvariantSkeleton.t.sol"
        skeleton_path.write_text(self._render(invariants, contracts, proof_plan or {}), encoding="utf-8")

        manifest_path = Path(session_dir) / "test_skeletons.json"
        manifest = {
            "harness_type": self.harness_type,
            "generated_files": [str(skeleton_path)],
            "invariant_ids": [str(inv.get("invariant_id")) for inv in invariants],
            "concrete_tests_generated": self._count_concrete_tests(invariants, contracts, proof_plan or {}),
        }
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        return {
            "test_skeletons": manifest_path,
            "test_skeleton_main": skeleton_path,
        }

    def collect_feedback(
        self,
        *,
        project_dir: Path,
        session_dir: Path,
        proof_plan: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        repo_dir = Path(project_dir)
        plan = proof_plan or {}
        cases = list(plan.get("proof_cases") or [])
        build = subprocess.run(
            ["forge", "build"],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            check=False,
        )
        if build.returncode != 0:
            results = [
                {
                    "case_id": case.get("case_id"),
                    "fingerprint": case.get("fingerprint"),
                    "test_name": self._test_name_for_case(case),
                    "status": "compile_failed",
                    "reason": (build.stderr or build.stdout or "").strip()[:400],
                    "loop_id": plan.get("loop_id", 0),
                }
                for case in cases
            ]
            return {
                "harness_type": self.harness_type,
                "results": results,
                "command": "forge build",
            }
        test = subprocess.run(
            ["forge", "test", "--match-contract", self.contract_name, "-vv"],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            check=False,
        )
        statuses = self._parse_foundry_statuses(test.stdout + "\n" + test.stderr)
        results = []
        for case in cases:
            test_name = self._test_name_for_case(case)
            status = statuses.get(test_name, "unknown")
            reason = ""
            if status == "failed":
                reason = "Generated proof test failed; invariant appears violated."
            elif status == "passed":
                reason = "Generated proof test passed; this path did not violate the invariant."
            elif status == "unknown":
                reason = "Foundry output did not include a definitive result for this proof case."
            results.append(
                {
                    "case_id": case.get("case_id"),
                    "fingerprint": case.get("fingerprint"),
                    "test_name": test_name,
                    "status": status,
                    "reason": reason,
                    "loop_id": plan.get("loop_id", 0),
                }
            )
        return {
            "harness_type": self.harness_type,
            "results": results,
            "command": "forge test --match-contract HoundInvariantSkeletonTest -vv",
        }

    def _render(self, invariants: list[dict[str, Any]], contracts: list[ContractSpec], proof_plan: dict[str, Any]) -> str:
        imports = sorted({c.import_path for c in contracts})
        lines = [
            "// SPDX-License-Identifier: MIT",
            "pragma solidity ^0.8.24;",
            "",
            "// Auto-generated by Hound. Fill in concrete setup/assertions before relying on these tests.",
        ]
        for path in imports:
            lines.append(f'import "{path}";')
        if imports:
            lines.append("")
        lines.extend([
            "contract HoundInvariantSkeletonTest {",
            "    receive() external payable {}",
            "",
        ])

        concrete_added = False
        proof_cases = list((proof_plan or {}).get("proof_cases") or [])
        if proof_cases:
            for case in proof_cases:
                rendered = self._render_case_from_plan(case, contracts)
                if rendered:
                    lines.extend(rendered)
                    concrete_added = True
        else:
            for inv in invariants:
                if not self._is_initialization_invariant(inv):
                    continue
                for contract in contracts:
                    if not contract.has_initialize or contract.constructor_arity > 0:
                        continue
                    for func in contract.functions:
                        lines.extend(self._render_init_gate_test(inv, contract, func))
                        concrete_added = True

        if concrete_added:
            lines.append("    // Remaining invariants without concrete test templates yet:")
            for inv in invariants:
                if self._is_initialization_invariant(inv):
                    continue
                lines.append(f"    // - {inv.get('invariant_id')}: {inv.get('statement')}")
            lines.append("")
        else:
            lines.append("    // No concrete invariant tests could be synthesized for this project yet.")
            lines.append("")

        for inv in invariants:
            if concrete_added and self._is_initialization_invariant(inv):
                continue
            inv_id = str(inv.get("invariant_id") or "inv")
            statement = str(inv.get("statement") or "Invariant under review")
            forbidden = str(inv.get("forbidden_effect") or "")
            check = ", ".join(str(c) for c in (inv.get("contrast_checks") or []))
            fn = self._fn_name(inv_id, statement)
            lines.extend([
                f"    function {fn}() public pure {{",
                f"        // Invariant: {statement}",
                f"        // Forbidden effect: {forbidden}",
                f"        // Contrast checks: {check}",
                "    }",
                "",
            ])
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _render_init_gate_test(self, inv: dict[str, Any], contract: ContractSpec, func: FunctionSpec) -> list[str]:
        inv_id = str(inv.get("invariant_id") or "inv")
        fn = f"test_{inv_id}_{contract.name}_{func.name}_blocked_before_initialize"
        call = f'abi.encodeWithSignature("{func.signature}"{func.args_expr})'
        if func.payable:
            exec_line = f"        (bool ok,) = address(target).call{{value: 1 wei}}({call});"
        else:
            exec_line = f"        (bool ok,) = address(target).call({call});"
        return [
            f"    function {fn}() public {{",
            f"        {contract.name} target = new {contract.name}();",
            exec_line,
            f'        require(!ok, "Expected init gate to block {contract.name}.{func.name} before initialize");',
            "    }",
            "",
        ]

    def _render_case_from_plan(self, case: dict[str, Any], contracts: list[ContractSpec]) -> list[str]:
        contract_name = str(case.get("contract_name") or "")
        function_name = str(case.get("function_name") or "")
        signature = str(case.get("function_signature") or "")
        invariant_id = str(case.get("invariant_id") or "inv")
        args_expr = self._normalize_plan_args(signature, str(case.get("args_expr") or ""))
        value_expr = case.get("value_expr")
        contract = next((c for c in contracts if c.name == contract_name), None)
        if contract is None or contract.constructor_arity > 0 or args_expr is None:
            return []
        fn = self._test_name_for_case(case)
        if value_expr:
            exec_line = f"        (bool ok,) = address(target).call{{value: {value_expr}}}(abi.encodeWithSignature(\"{signature}\"{args_expr}));"
        else:
            exec_line = f"        (bool ok,) = address(target).call(abi.encodeWithSignature(\"{signature}\"{args_expr}));"
        return [
            f"    function {fn}() public {{",
            f"        {contract_name} target = new {contract_name}();",
            exec_line,
            f'        require(!ok, "Expected proof case to fail: {contract_name}.{function_name}");',
            "    }",
            "",
        ]

    def _test_name_for_case(self, case: dict[str, Any]) -> str:
        case_id = str(case.get("case_id") or "")
        if case_id:
            slug = re.sub(r"[^A-Za-z0-9_]+", "_", case_id).strip("_")
            return f"test_{slug}"
        invariant_id = str(case.get("invariant_id") or "inv")
        contract_name = str(case.get("contract_name") or "Contract")
        function_name = str(case.get("function_name") or "proof")
        return f"test_{invariant_id}_{contract_name}_{function_name}_proof"

    def _parse_foundry_statuses(self, output: str) -> dict[str, str]:
        statuses: dict[str, str] = {}
        pattern = re.compile(r"\[(PASS|FAIL)[^\]]*\]\s+(test_[A-Za-z0-9_]+)\(")
        for match in pattern.finditer(output or ""):
            statuses[match.group(2)] = "passed" if match.group(1) == "PASS" else "failed"
        return statuses

    def _normalize_plan_args(self, signature: str, args_expr: str) -> str | None:
        raw = (args_expr or "").strip()
        if signature.endswith("()"):
            return ""
        if raw in {"", "()"}:
            return ""
        if ";" in raw:
            return None
        if raw.startswith("[") or "new address[](" in raw or "new uint" in raw:
            return None
        raw = raw.replace("address(delegateTarget)", "address(new DelegateTarget())")
        if raw.count("(") != raw.count(")"):
            return None
        if raw.startswith(","):
            return raw
        return ", " + raw

    def _scan_contracts(self, repo_dir: Path) -> list[ContractSpec]:
        contracts: list[ContractSpec] = []
        src_dir = repo_dir / "src"
        if not src_dir.exists():
            return contracts
        for sol_file in sorted(src_dir.rglob("*.sol")):
            rel = sol_file.relative_to(repo_dir).as_posix()
            text = sol_file.read_text(encoding="utf-8")
            for contract_name in re.findall(r"\bcontract\s+([A-Za-z_][A-Za-z0-9_]*)", text):
                contracts.append(
                    ContractSpec(
                        name=contract_name,
                        import_path="../../" + rel,
                        has_initialize="function initialize(" in text or " initialized;" in text or " initialized " in text,
                        constructor_arity=self._constructor_arity(text),
                        functions=self._parse_functions(text),
                    )
                )
        return contracts

    def _parse_functions(self, text: str) -> list[FunctionSpec]:
        out: list[FunctionSpec] = []
        pattern = re.compile(r"function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*([^{};]*)", re.MULTILINE)
        for name, params, tail in pattern.findall(text):
            lower_tail = tail.lower()
            if "public" not in lower_tail and "external" not in lower_tail:
                continue
            if "view" in lower_tail or "pure" in lower_tail:
                continue
            if name == "initialize":
                continue
            args_expr = self._default_args_expr(params)
            if args_expr is None:
                continue
            out.append(
                FunctionSpec(
                    name=name,
                    signature=f"{name}({self._signature_types(params)})",
                    args_expr=args_expr,
                    payable="payable" in lower_tail,
                )
            )
        return out

    def _constructor_arity(self, text: str) -> int:
        match = re.search(r"constructor\s*\(([^)]*)\)", text)
        if not match:
            return 0
        return len([p.strip() for p in match.group(1).split(",") if p.strip()])

    def _signature_types(self, params: str) -> str:
        return ",".join(self._normalize_type(p) for p in params.split(",") if p.strip())

    def _default_args_expr(self, params: str) -> str | None:
        items = [p.strip() for p in params.split(",") if p.strip()]
        if not items:
            return ""
        values: list[str] = []
        for item in items:
            expr = self._default_value_expr(self._normalize_type(item))
            if expr is None:
                return None
            values.append(expr)
        return ", " + ", ".join(values)

    def _normalize_type(self, param: str) -> str:
        p = re.sub(r"\b(calldata|memory|storage|indexed)\b", "", param)
        p = re.sub(r"\s+", " ", p).strip()
        tokens = p.split(" ")
        if not tokens:
            return ""
        base = tokens[0]
        if base == "address":
            return "address[]" if "[]" in p else "address"
        if "[]" in p:
            return base + "[]"
        return base

    def _default_value_expr(self, ptype: str) -> str | None:
        if ptype in {"uint256", "uint128", "uint64", "uint32", "uint16", "uint8", "uint", "int256", "int128", "int64", "int32", "int16", "int8", "int"}:
            return "uint256(1)"
        if ptype == "bool":
            return "true"
        if ptype == "address":
            return "address(this)"
        if ptype == "bytes":
            return 'hex""'
        if ptype == "string":
            return '"hound"'
        if ptype == "address[]":
            return "new address[](0)"
        if ptype in {"uint256[]", "uint[]"}:
            return "new uint256[](0)"
        if ptype == "bytes[]":
            return "new bytes[](0)"
        return None

    def _is_initialization_invariant(self, inv: dict[str, Any]) -> bool:
        text = " ".join(str(inv.get(key) or "") for key in ("statement", "forbidden_effect")).lower()
        return "initializ" in text and "before" in text

    def _count_concrete_tests(self, invariants: list[dict[str, Any]], contracts: list[ContractSpec], proof_plan: dict[str, Any]) -> int:
        proof_cases = list((proof_plan or {}).get("proof_cases") or [])
        if proof_cases:
            return len(proof_cases)
        if not any(self._is_initialization_invariant(inv) for inv in invariants):
            return 0
        total = 0
        for contract in contracts:
            if contract.has_initialize and contract.constructor_arity == 0:
                total += len(contract.functions)
        return total

    def _fn_name(self, invariant_id: str, statement: str) -> str:
        slug = re.sub(r"[^A-Za-z0-9]+", "_", statement).strip("_")
        slug = re.sub(r"_+", "_", slug)
        slug = slug[:80] or "Invariant"
        return f"test_{invariant_id}_{slug}"


class SkeletonWriterRegistry:
    """Resolve harness-specific test writers."""

    def __init__(self):
        self._writers = {
            "foundry": FoundrySkeletonWriter(),
        }

    def get(self, harness_type: str):
        return self._writers.get(str(harness_type or "").lower())
